[project]
name = "bitcoin-quant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas>=2.3.3",
    "plotly>=6.5.0",
    "ta>=0.11.0",
    "yfinance>=0.2.66",
]
